const latexEquations = [
    {name: 'Fraction', equation: '\\frac{}{}', text: 'frac',fontSize: '200%',textSize: '100%',topPos: '80%'},
    {name: 'Square Root', equation: '\\sqrt{}', text: 'sqrt',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Square Root 2', equation: '\\sqrt[]{}', text: 'sqrt',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Integration', equation: '\\int', text: 'int',fontSize: '170%',textSize: '100%',topPos: '80%'},
    {name: 'Summation', equation: '\\sum', text: 'sum',fontSize: '130%',textSize: '100%',topPos: '80%'},
    {name: 'Pi-Product', equation: '\\prod', text: 'prod',fontSize: '130%',textSize: '100%',topPos: '80%'},
    {name: 'Power', equation: 'x\\^{}', text: '^',fontSize: '300%',textSize: '150%',topPos: '70%'},
    {name: 'Underscore', equation: 'x\\_{}', text: '_',fontSize: '300%',textSize: '150%',topPos: '70%'},
    {name: 'Multiplication', equation: '\\times', text: 'times',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Division', equation: '\\div', text: 'div',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Plus-Minus', equation: '\\pm', text: 'pm',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Minus-Plus', equation: '\\mp', text: 'mp',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Intersection', equation: '\\cap', text: 'cap',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Union', equation: '\\cup', text: 'cup',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Null', equation: '\\varnothing', text: 'varnothing',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'XOR', equation: '\\oplus', text: 'oplus',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'OTimes', equation: '\\otimes', text: 'otimes',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Subset', equation: '\\subset', text: 'subset',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Supset', equation: '\\supset', text: 'supset',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Less Than or Equal To', equation: '\\le', text: 'le',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Greater Than or Equal To', equation: '\\ge', text: 'ge',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Therefore', equation: '\\therefore', text: 'therefore',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Wedge', equation: '\\wedge', text: 'wedge',fontSize: '300%',textSize: '100%',topPos: '80%'},
    {name: 'Vee', equation: '\\vee', text: 'vee',fontSize: '300%',textSize: '100%',topPos: '80%'},
];

export default latexEquations;